Repository ge-high-assurance/RITE, pull requests merged in 2023-08, with the labels that each got.

#93 Adding scrollbars to Nodegroup Store View
  tools/rack/rack.plugin/src/com/ge/research/rack/views/NodegroupsView.java
Labels: enhancement

#95 Separates creating zip and uploading into two separate actions
  tools/rack/rack.plugin/plugin.xml
  tools/rack/rack.plugin/src/com/ge/research/rack/UploadIngestionPackageHandler.java
  tools/rack/rack.plugin/src/com/ge/research/rack/ZipIngestionPackageHandler.java
Labels: enhancement, high-priority

#104 Fixing the sizing of components in the Ontology View
  tools/rack/rack.plugin/src/com/ge/research/rack/views/OntologyTreeView.java
Labels: bug

#121 RITE-120: Bug: Misleading "Save Ingestion Package as Zip" error
  tools/rack/rack.plugin/src/com/ge/research/rack/UploadIngestionPackageHandler.java
Labels: bug
